FROM golang:1.22.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download 

COPY . .

RUN go get -u github.com/gin-gonic/go 

RUN go get -u github.com/streadway/ampq

RUN go build -o main .

EXPOSE 8080

CMD [ "./main" ]

